---
title: "simulate_hdf5_accuracy"
author: "Yuwei Ni"
date: "3/10/2019"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
# package
library(mbkmeans)
library(rhdf5)
library(scater)
#library(profvis)
library(mclust)
library(dplyr)
library(cowplot)
library(parallel)
library(HDF5Array)


# can see how many cores are available
detectCores() 

# number of cores for parallelization
cores <- 1
B <- 3

```

```{r functions}
#simulate_gauss_mix
simulate_gauss_mix <- function(n_cells, n_genes,
                               k = 3, x_mus = c(0,5,5), 
                               x_sds = c(1,0.1,1), 
                               y_mus = c(5,5,0), 
                               y_sds = c(1,0.1,1), 
                               prop1 = c(0.3,0.5,0.2))
{ 
  
  if(k != length(x_mus)){stop("k is not same as length of x_mus")} 
  if(k != length(x_sds)){stop("k is not same as length of x_sds")} 
  if(k != length(y_mus)){stop("k is not same as length of y_mus")} 
  if(k != length(y_sds)){stop("k is not same as length of y_sds")} 
  if(k != length(prop1)){stop("k is not same as length of prop1")} 
  
  comp1 <- sample(seq_len(k), prob=prop1, size=n_cells, replace=TRUE)
  
  # Sampling locations for cells in each component
  samples1 <- cbind(rnorm(n=n_cells, mean=x_mus[comp1],sd=x_sds[comp1]),
                    rnorm(n=n_cells, mean=y_mus[comp1],sd=y_sds[comp1]))
  
  # Random projection to D dimensional space, to mimic high-dimensional expression data.
  proj <- matrix(rnorm(n_genes*n_cells), nrow=n_genes, ncol=2)
  A1 <- samples1 %*% t(proj)
  
  # Add normally distributed noise.
  A1 <- A1 + rnorm(n_genes*n_cells)
  rownames(A1) <- paste0("Cell", seq_len(n_cells), "-1")
  colnames(A1) <- paste0("Gene", seq_len(n_genes))

  list("true_center" = cbind("x" = x_mus, "y" = y_mus),
       "true_cluster_id" = comp1,
       "true_data" = samples1, 
       "obs_data" = A1)
}




#' @title bench_hdf5
#' @param i monte carlo simulation iteration
#' @param method  kmeans, mbkmeans_nohdf5, mbkmeans_hdf5
bench_hdf5 <- function(i, n_cells, 
                           n_genes, k_centers, 
                           batch_size=batch_size, 
                           num_init = num_init, 
                           max_iters = max_iters, 
                           init_fraction = init_fraction, 
                           initializer = initializer, 
                       method = "kmeans", ...) {
    # simulate data 
    sim_data <- simulate_gauss_mix(n_cells=n_cells, 
                                   n_genes=n_genes)
    sim_data_hdf5 <- as(as.matrix(sim_data$obs_data),"HDF5Matrix")
    
    # save the hdf5 matrix into a file on-disk 
    
    # apply clustering methods 
    if(method == "kmeans"){ 
      kmeans_time <- system.time(kmeans_output <- stats::kmeans(sim_data$obs_data, 
                                   centers=k_centers))[3]
    }
    
    
     mbkmeans_time <- system.time(mbkmeans_output <- mbkmeans::mini_batch(
            sim_data$obs_data, clusters = k_centers, 
            batch_size = batch_size, num_init = num_init, 
            max_iters = max_iters, init_fraction = init_fraction,
            initializer = initializer, ...))[3]
    
    # this function needs to be adjusted to point to the HDF5 matrix on disk
    mbkmeans_hdf5_time <- system.time(mbkmeans_hdf5_output <- mbkmeans::mini_batch(
            sim_data_hdf5, clusters = k_centers, 
            batch_size = batch_size, num_init = num_init, 
            max_iters = max_iters, init_fraction = init_fraction,
            initializer = initializer, ...))[3]

    list(sim_data = sim_data, 
         kmeans_output = kmeans_output,
         mbkmeans_output = mbkmeans_output,
         mbkmeans_hdf5_output = mbkmeans_hdf5_output,
         kmeans_time = kmeans_time,
         mbkmeans_time = mbkmeans_time,
         mbkmeans_hdf5_time = mbkmeans_hdf5_time)    
}

#bench_accuracy_calculate_ari
# maybe consider using something else beside plyr:ldply ? 
bench_accuracy_calculate_ari <- function(sim_object){
  out <- plyr::ldply(sim_object, function(xx){
    ari_kmeans <- mclust::adjustedRandIndex(
            xx$sim_data$true_cluster_id, 
            as.numeric(xx$kmeans_output$cluster))
    
    ari_mbkmeans <- mclust::adjustedRandIndex(
            xx$sim_data$true_cluster_id,
            xx$mbkmeans_output$Clusters)
    
    ari_mbkmeans_hdf5 <- mclust::adjustedRandIndex(
            xx$sim_data$true_cluster_id,
            xx$mbkmeans_hdf5_output$Clusters)
  c(ari_kmeans=ari_kmeans, ari_mbkmeans=ari_mbkmeans,ari_mbkmeans_hdf5=ari_mbkmeans_hdf5) 
  })
  return(out)
}

#bench_accuracy_extract_wcss
bench_accuracy_extract_wcss <- function(sim_object){
  out <- plyr::ldply(sim_object, function(xx){
    wcss_kmeans <- sum(xx$kmeans_output$withinss)
    wcss_mbkmeans <- sum(xx$mbkmeans_output$WCSS_per_cluster)
    wcss_mbkmeans_hdf5 <- sum(xx$mbkmeans_hdf5_output$WCSS_per_cluster)
    c(wcss_kmeans =wcss_kmeans, wcss_mbkmeans = wcss_mbkmeans,wcss_mbkmeans_hdf5=wcss_mbkmeans_hdf5)
  })
  return(out)
}

#bench_time_extract
bench_time_extract <- function(sim_object){
  out <- plyr::ldply(sim_object, function(xx){
    time_kmeans <- xx$kmeans_time
    time_mbkmeans <- xx$mbkmeans_time
    time_mbkmeans_hdf5 <- xx$mbkmeans_hdf5_time
    c(time_kmeans =time_kmeans, time_mbkmeans = time_mbkmeans,time_mbkmeans_hdf5=time_mbkmeans_hdf5)
  })
  return(out)
}

```

```{r data}
#data
nC <- 1000
nG <- 500
mbkmeans_initializer = "random"
```

### `batch_size = 1` (or .1 percent of data)
```{r .1%}
print(Sys.time())

# simulate data to assess accuracy
batch_percent <- 0.001
save_bs_0001 <- mclapply(seq_len(B),
                  n_cells = nC, n_genes = nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE, 
                  method = "kmeans")

save_bs_0001 <- mclapply(seq_len(B),
                  n_cells = nC, n_genes = nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE, 
                  method = "mbkmeans_nohdf5")

save_bs_0001 <- mclapply(seq_len(B),
                  n_cells = nC, n_genes = nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE, 
                  method = "mbkmeans_nohdf5")



# calculate adjusted Rand Index 
ari_output_bs_0001_ari <- as.data.frame(bench_accuracy_calculate_ari(save_bs_0001))

# extract wcss
ari_output_bs_0001_wcss <- as.data.frame(bench_accuracy_extract_wcss(save_bs_0001))

# extract compute time
time_output_bs_0001 <- as.data.frame(bench_time_extract(save_bs_0001))

# add in columns for batch size and iteration time (B)
#ari
ari_output_bs_0001_ari <- data.frame(iteration = rownames(ari_output_bs_0001_ari),ari_output_bs_0001_ari)

ari_output_bs_0001_ari <- cbind(batch_size = batch_percent, ari_output_bs_0001_ari)

#wcss
ari_output_bs_0001_wcss <- data.frame(iteration = rownames(ari_output_bs_0001_wcss),ari_output_bs_0001_wcss)

ari_output_bs_0001_wcss <- cbind(batch_size = batch_percent, ari_output_bs_0001_wcss)

#time
time_output_bs_0001 <- data.frame(iteration = rownames(time_output_bs_0001),time_output_bs_0001)

time_output_bs_0001 <- cbind(batch_size = batch_percent, time_output_bs_0001)

```

### `batch_size = 5` (or .5 percent of data)

```{r .5%}
# simulate data
batch_percent <- 0.005
save_bs_0005 <- mclapply(seq_len(B), 
                  n_cells = nC, n_genes = nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE)

# calculate adjusted Rand Index 
ari_output_bs_0005_ari <- as.data.frame(bench_accuracy_calculate_ari(save_bs_0005))

# extract wcss
ari_output_bs_0005_wcss <- as.data.frame(bench_accuracy_extract_wcss(save_bs_0005))


# extract compute time
time_output_bs_0005 <- as.data.frame(bench_time_extract(save_bs_0005))

# add in columns for batch size and iteration time (B)
#ari
ari_output_bs_0005_ari <- data.frame(iteration = rownames(ari_output_bs_0005_ari),ari_output_bs_0005_ari)

ari_output_bs_0005_ari <- cbind(batch_size = batch_percent, ari_output_bs_0005_ari)

#wcss
ari_output_bs_0005_wcss <- data.frame(iteration = rownames(ari_output_bs_0005_wcss),ari_output_bs_0005_wcss)

ari_output_bs_0005_wcss <- cbind(batch_size = batch_percent, ari_output_bs_0005_wcss)

#time
time_output_bs_0005 <- data.frame(iteration = rownames(time_output_bs_0005),time_output_bs_0005)

time_output_bs_0005 <- cbind(batch_size = batch_percent, time_output_bs_0005)

```

### `batch_size = 10` (or 1 percent of data)
```{r 1%}
# simulate data
batch_percent <- 0.01
save_bs_001 <- mclapply(seq_len(B), n_cells=nC, n_genes =nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE)

# calculate adjusted Rand Index 
ari_output_bs_001_ari <- as.data.frame(bench_accuracy_calculate_ari(save_bs_001))

# extract wcss
ari_output_bs_001_wcss <- as.data.frame(bench_accuracy_extract_wcss(save_bs_001))

# extract compute time
time_output_bs_001 <- as.data.frame(bench_time_extract(save_bs_001))

# add in columns for batch size and iteration time (B)
#ari
ari_output_bs_001_ari <- data.frame(iteration = rownames(ari_output_bs_001_ari),ari_output_bs_001_ari)

ari_output_bs_001_ari <- cbind(batch_size = batch_percent, ari_output_bs_001_ari)

#wcss
ari_output_bs_001_wcss <- data.frame(iteration = rownames(ari_output_bs_001_wcss),ari_output_bs_001_wcss)

ari_output_bs_001_wcss <- cbind(batch_size = batch_percent, ari_output_bs_001_wcss)

#time
time_output_bs_001 <- data.frame(iteration = rownames(time_output_bs_001),time_output_bs_001)

time_output_bs_001 <- cbind(batch_size = batch_percent, time_output_bs_001)
```


### `batch_size = 50` (or 5 percent of data)
```{r 5%}
# simulate data
batch_percent <- 0.05
save_bs_005 <- mclapply(seq_len(B), n_cells=nC, n_genes =nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE)

# calculate adjusted Rand Index 
ari_output_bs_005_ari <- as.data.frame(bench_accuracy_calculate_ari(save_bs_005))

# extract wcss
ari_output_bs_005_wcss <- as.data.frame(bench_accuracy_extract_wcss(save_bs_005))


# extract compute time
time_output_bs_005 <- as.data.frame(bench_time_extract(save_bs_005))

# add in columns for batch size and iteration time (B)
#ari
ari_output_bs_005_ari <- data.frame(iteration = rownames(ari_output_bs_005_ari),ari_output_bs_005_ari)

ari_output_bs_005_ari <- cbind(batch_size = batch_percent, ari_output_bs_005_ari)

#wcss
ari_output_bs_005_wcss <- data.frame(iteration = rownames(ari_output_bs_005_wcss),ari_output_bs_005_wcss)

ari_output_bs_005_wcss <- cbind(batch_size = batch_percent, ari_output_bs_005_wcss)

#time
time_output_bs_005 <- data.frame(iteration = rownames(time_output_bs_005),time_output_bs_005)

time_output_bs_005 <- cbind(batch_size = batch_percent, time_output_bs_005)
```

### `batch_size = 250` (or 25 percent of data)
```{r 25%}
# simulate data
batch_percent <- 0.25
save_bs_025 <- mclapply(seq_len(B), n_cells=nC, n_genes =nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE)

# calculate adjusted Rand Index 
ari_output_bs_025_ari <- as.data.frame(bench_accuracy_calculate_ari(save_bs_025))

# extract wcss
ari_output_bs_025_wcss <- as.data.frame(bench_accuracy_extract_wcss(save_bs_025))


# extract compute time
time_output_bs_025 <- as.data.frame(bench_time_extract(save_bs_025))

# add in columns for batch size and iteration time (B)
#ari
ari_output_bs_025_ari <- data.frame(iteration = rownames(ari_output_bs_025_ari),ari_output_bs_025_ari)

ari_output_bs_025_ari <- cbind(batch_size = batch_percent, ari_output_bs_025_ari)

#wcss
ari_output_bs_025_wcss <- data.frame(iteration = rownames(ari_output_bs_025_wcss),ari_output_bs_025_wcss)

ari_output_bs_025_wcss <- cbind(batch_size = batch_percent, ari_output_bs_025_wcss)

#time
time_output_bs_025 <- data.frame(iteration = rownames(time_output_bs_025),time_output_bs_025)

time_output_bs_025 <- cbind(batch_size = batch_percent, time_output_bs_025)
```

### `batch_size = 500` (or 50 percent of data)
```{r 50%}
# simulate data
batch_percent <- 0.50
save_bs_050 <- mclapply(seq_len(B), n_cells=nC, n_genes =nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE)

# calculate adjusted Rand Index 
ari_output_bs_050_ari <- as.data.frame(bench_accuracy_calculate_ari(save_bs_050))

# extract wcss
ari_output_bs_050_wcss <- as.data.frame(bench_accuracy_extract_wcss(save_bs_050))

# extract compute time
time_output_bs_050 <- as.data.frame(bench_time_extract(save_bs_050))

# add in columns for batch size and iteration time (B)
#ari
ari_output_bs_050_ari <- data.frame(iteration = rownames(ari_output_bs_050_ari),ari_output_bs_050_ari)

ari_output_bs_050_ari <- cbind(batch_size = batch_percent, ari_output_bs_050_ari)

#wcss
ari_output_bs_050_wcss <- data.frame(iteration = rownames(ari_output_bs_050_wcss),ari_output_bs_050_wcss)

ari_output_bs_050_wcss <- cbind(batch_size = batch_percent, ari_output_bs_050_wcss)

#time
time_output_bs_050 <- data.frame(iteration = rownames(time_output_bs_050),time_output_bs_050)

time_output_bs_050 <- cbind(batch_size = batch_percent, time_output_bs_050)
```

```{r 99%}
# simulate data
batch_percent <- 0.99
save_bs_99 <- mclapply(seq_len(B), n_cells=nC, n_genes =nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE)

# calculate adjusted Rand Index 
ari_output_bs_99_ari <- as.data.frame(bench_accuracy_calculate_ari(save_bs_99))

# extract wcss
ari_output_bs_99_wcss <- as.data.frame(bench_accuracy_extract_wcss(save_bs_99))

# extract compute time
time_output_bs_99 <- as.data.frame(bench_time_extract(save_bs_99))

# add in columns for batch size and iteration time (B)
#ari
ari_output_bs_99_ari <- data.frame(iteration = rownames(ari_output_bs_99_ari),ari_output_bs_99_ari)

ari_output_bs_99_ari <- cbind(batch_size = batch_percent, ari_output_bs_99_ari)

#wcss
ari_output_bs_99_wcss <- data.frame(iteration = rownames(ari_output_bs_99_wcss),ari_output_bs_99_wcss)

ari_output_bs_99_wcss <- cbind(batch_size = batch_percent, ari_output_bs_99_wcss)

#time
time_output_bs_99 <- data.frame(iteration = rownames(time_output_bs_99),time_output_bs_99)

time_output_bs_99 <- cbind(batch_size = batch_percent, time_output_bs_99)
```

### `batch_size = 1000` (or 100 percent of data)
```{r 100%, warning=FALSE}
# simulate data
batch_percent <- 1
save_bs_100 <- mclapply(seq_len(B), n_cells=nC, n_genes =nG, 
                  bench_hdf5, k_centers = 3,
                  batch_size = nC*batch_percent, num_init = 10, max_iters = 100, 
                  init_fraction = .1, initializer = mbkmeans_initializer, 
                  mc.cores=cores, calc_wcss = TRUE)

# calculate adjusted Rand Index 
ari_output_bs_100_ari <- as.data.frame(bench_accuracy_calculate_ari(save_bs_100))

# extract wcss
ari_output_bs_100_wcss <- as.data.frame(bench_accuracy_extract_wcss(save_bs_100))

# extract compute time
time_output_bs_100 <- as.data.frame(bench_time_extract(save_bs_100))

# add in columns for batch size and iteration time (B)
#ari
ari_output_bs_100_ari <- data.frame(iteration = rownames(ari_output_bs_100_ari),ari_output_bs_100_ari)

ari_output_bs_100_ari <- cbind(batch_size = batch_percent, ari_output_bs_100_ari)

#wcss
ari_output_bs_100_wcss <- data.frame(iteration = rownames(ari_output_bs_100_wcss),ari_output_bs_100_wcss)

ari_output_bs_100_wcss <- cbind(batch_size = batch_percent, ari_output_bs_100_wcss)

#time
time_output_bs_100 <- data.frame(iteration = rownames(time_output_bs_100),time_output_bs_100)

time_output_bs_100 <- cbind(batch_size = batch_percent, time_output_bs_100)
```

```{r}
# Combine the outputs
ari_total <- do.call("rbind", list(ari_output_bs_0001_ari,ari_output_bs_0005_ari,ari_output_bs_001_ari, ari_output_bs_005_ari, ari_output_bs_025_ari,ari_output_bs_050_ari,ari_output_bs_99_ari,ari_output_bs_100_ari))

wcss_total <- do.call("rbind", list(ari_output_bs_0001_wcss,ari_output_bs_0005_wcss,ari_output_bs_001_wcss,ari_output_bs_005_wcss,ari_output_bs_025_wcss,ari_output_bs_050_wcss,ari_output_bs_99_wcss,ari_output_bs_100_wcss))

time_total <- do.call("rbind", list(time_output_bs_0001,time_output_bs_0005,time_output_bs_001,time_output_bs_005,time_output_bs_025,time_output_bs_050,time_output_bs_99,time_output_bs_100))
```

```{r}
time <- format(Sys.time(), "%Y-%m-%d_%H-%M-%S")
dir_name <- sprintf("Simulation_%s", time)

if(!dir.exists(dir_name)) {
  dir.create(dir_name)
}
```

```{r}
setwd(dir_name)
sim_info <- data.frame(
  Col1 = c("Number of Cores:","Monte Carlo Simulation Interation:",
           "Number of Cells:","Number of Genes:"),
  Col2 = c(cores, B, nC, nG)
)

write.table(sim_info, file = "Simulation_Info.txt", append = FALSE, sep = " ", dec = ".",
            row.names = FALSE, col.names = FALSE)

write.table(ari_total, file = "ARI_Summary.txt", append = FALSE, sep = " ", dec = ".",
            row.names = FALSE, col.names = TRUE)

write.table(wcss_total, file = "WCSS_Summary.txt", append = FALSE, sep = " ", dec = ".",
            row.names = FALSE, col.names = TRUE)

write.table(time_total, file = "Time_Summary.txt", append = FALSE, sep = " ", dec = ".",
            row.names = FALSE, col.names = TRUE)
```

```{r}
#to get information about RAM and CPUs on machine
#library(benchmarkme) 
#print(get_ram())
#print(get_cpu())
#print(BiocManager::version())
#print(sessionInfo())
```

