---
title: "Real Data Analysis Summary"
author: "Ruoxi Liu"
date: "9/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 14, fig.height = 10)
```

```{r}
library(tidyverse)
library(here)
library(purrr)
library(cowplot)
```

List files from `_stephanie_cluster.csv` and `_davide.csv`

```{r}
sh_files <- list.files(here("main", "case_studies", "output"), 
                          pattern = "_stephanie_cluster.csv")
# dr_files <- list.files(here("main", "case_studies", "output"), 
#                           pattern = "_davide.csv")
```

Read in files from `_stephanie_cluster.csv`
```{r}
colnames_memory <- c("dataset", "run", "ncells", "ngenes", "step", 
                   "method", "batch_prop", "B", "max_mem")
colnames_time <- c("dataset", "run", "ncells", "ngenes", "step", 
                   "method", "batch_prop", "B", "user_time", 
                   "system_time", "elapsed_time")
colnames_wcss <- c("dataset", "run", "ncells", "ngenes", "step", 
                   "method", "batch_prop", "B", "WCSS")

pef_results <- vector("list", length(analysis_type))
for(ty in analysis_type){
  tmp <- sh_files[grep(ty, sh_files)] %>% 
            map(read_csv, col_names = FALSE) %>% 
            bind_rows()
  
  if(ty == "memory"){ colnames(tmp) <- colnames_memory }
  if(ty == "time"){ colnames(tmp) <- colnames_time }
  if(ty == "wcss"){ colnames(tmp) <- colnames_wcss }
  
  pef_results[[ty]] <- tmp
}
```

Convert three datasets into one long dataset

```{r}
pef_results$time <- 
  pef_results$time %>% 
  tidyr::pivot_longer(cols = -c(dataset:B), 
                      names_to = "time_type", 
                      values_to = "time")
sh_results <- dplyr::left_join(pef_results$time, pef_results$memory)
sh_results <- dplyr::left_join(sh_results, pef_results$wcss)

sh_results$dataset <- 
  forcats::fct_reorder(sh_results$dataset, sh_results$ncells, .desc = FALSE)
sh_results$batch_prop <- factor(sh_results$batch_prop)
sh_results 
```

From here we could combine the `_stephanie_cluster.csv` and `_davide.csv`
datasets

```{r, eval=FALSE}
final_results <- rbind(sh_results, dr_results)
```

For now I'll just go with only using `sh_results`
```{r}
final_results <- sh_results
```

Ready for plots! 

ok still need to add different lines for different `batch_prop`
```{r}
final_results %>% 
  ggplot(aes(x = dataset, y = max_mem, color = method)) + 
  geom_point() + 
  ylab("Memory (Mb)") + 
  theme(legend.position = "top", legend.justification= "center") +
  scale_color_discrete(name = "Method")
```


```{r}
final_results %>% 
  dplyr::filter(time_type == "elapsed_time") %>%
  ggplot(aes(x = dataset, y = time/60, color = method)) + 
  geom_point() + 
  ylab("Time (minutes)") + 
  theme(legend.position = "top", legend.justification= "center") +
  scale_color_discrete(name = "Method")
```

```{r}
final_results %>% 
  ggplot(aes(x = dataset, y = WCSS, color = method)) + 
  geom_point() + 
  ylab("WCSS") + 
  theme(legend.position = "top", legend.justification= "center") +
  scale_color_discrete(name = "Method")
```