---
title: "chunksize"
author: "Ruoxi Liu"
date: "6/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width = 12, fig.height = 10)
```

```{r}
library(tidyr)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(grid)
library(here)
```

```{r}
files <- list.files(path= here("ongoing_analysis","ChunkTest/TENxBrainData/Output"), pattern="^time_[a-z]+.csv", full.names=TRUE, recursive=FALSE)
time_table <- NULL
for (i in (1:length(files))){
  temp_table <- read.csv(file = files[i], header=TRUE, sep=",")
  time_table <- rbind(time_table, temp_table)
}

files <- list.files(path= here("ongoing_analysis","ChunkTest/TENxBrainData/Output"), pattern="^mem_[a-z]+.csv", full.names=TRUE, recursive=FALSE)
mem_table <- NULL
for (i in (1:length(files))){
  temp_table <- read.csv(file = files[i], header=TRUE, sep=",")
  mem_table <- rbind(mem_table, temp_table)
}
```

```{r}
time_table[,1:6] %>% 
  dplyr::group_by(geometry, observations, abs.batch.size) %>% 
  #dplyr::summarize(mean = mean(time), 
   #                sd = sd(time)) %>% 
  ggplot(aes(x = as.factor(abs.batch.size), y = time, color = geometry)) +
          #geom_line()+
          geom_point()+
          labs(title = "HDF5 Geometry: Time") + 
  facet_wrap(~observations)
```
```{r}
mem_table[,1:6] %>% 
  dplyr::group_by(geometry, observations, abs.batch.size) %>% 
  #dplyr::filter(observations == 75000) %>%
  #dplyr::summarize(mean = mean(time), 
   #                sd = sd(time)) %>% 
  ggplot(aes(x = as.factor(abs.batch.size), y = memory*.001, color = geometry)) +
          #geom_line()+
          geom_point()+
          labs(title = "HDF5 Geometry: Memory") + 
  facet_wrap(~observations)
```

```{r include=FALSE}
files <- list.files(path= here("ongoing_analysis","ChunkTest"), pattern="*.csv", full.names=TRUE, recursive=FALSE)

final_table <- NULL

for (i in (1:length(files))){
  temp_table <- read.csv(file = files[i], header=TRUE, sep=",")[,1:5]
  final_table <- rbind(final_table, temp_table)
}
```

```{r include=FALSE}
final_table %>% 
  dplyr::group_by(dimension, observations, batch_size) %>% 
  dplyr::summarize(mean = mean(time), 
                   sd = sd(time)) %>% 
  ggplot(aes(x = observations, y = mean, color = dimension)) +
          geom_line()+
          geom_point()+
          geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                position=position_dodge(0.05))+
        labs(title = "Observation vs. time w/ increading Batch Size") + 
  facet_wrap(~batch_size)
```

```{r include=FALSE}
final_table %>% 
  #dplyr::filter(dimension != "one") %>%
  dplyr::filter(observations < 250000) %>%
  dplyr::group_by(dimension, observations, batch_size) %>% 
  dplyr::summarize(mean = mean(time), 
                   sd = sd(time)) %>% 
  ggplot(aes(x = observations, y = mean, color = dimension)) +
          geom_line()+
          geom_point()+
          geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                position=position_dodge(0.05))+
        labs(title = "Observation vs. time w/ increading Batch Size") + 
  facet_wrap(~batch_size)
```

