---
title: "Test-WCSS"
author: "Ruoxi Liu"
date: "7/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(HDF5Array)
library(here)
library(mbkmeans)
```

```{r}
data_name <- "hca_bonemarrow"
k <- 15
batch <- 0.01
```

```{r}
#sce <- loadHDF5SummarizedExperiment(dir = here("main/case_studies/data/full", data_name, paste0(data_name, "_preprocessed")), prefix="")

#set.seed(1234)
#keep_cells <- sample(1:ncol(sce),size = 300000)
#set.seed(1234)
#keep_genes <- sample(1:nrow(sce),size = 3000)
#sce_test <- sce[keep_genes,keep_cells]
#sce_test

#saveHDF5SummarizedExperiment(sce_test, 
#                             dir = here("main/case_studies/data/full/hca_bonemarrow","hca_bonemarrow_300000x3000"),
#                             prefix="", replace=FALSE, 
#                             chunkdim=c(dim(counts(sce_test))[1],1), 
#                             level=NULL, verbose=FALSE)
```

```{r}
test_list <- c(1000,5000,10000,50000,100000)
wcss_list <- c()
for (i in test_list){
  hca <- loadHDF5SummarizedExperiment(dir = here("main/case_studies/data/full/hca_bonemarrow", paste0("hca_bonemarrow_", i, "x3000")), prefix="")
  set.seed(1234)
  wcss <- mbkmeans(counts(hca), clusters=k, batch_size = as.integer(dim(counts(hca))[2]*batch), calc_wcss = TRUE)$WCSS_per_cluster
  wcss_list <- c(wcss_list, sum(wcss))
  rm(hca)
}
print(wcss_list)
```

```{r}
plot(test_list, wcss_list)
```
```{r}
test_list <- c(1000,5000,10000,50000,100000)
wcss_list_km <- c()
for (i in test_list){
  hca <- loadHDF5SummarizedExperiment(dir = here("main/case_studies/data/full/hca_bonemarrow", paste0("hca_bonemarrow_", i, "x3000")), prefix="")
  hca_matrix <- t(as.matrix(counts(hca)))
  set.seed(1234)
  wcss <- stats::kmeans(hca_matrix, centers=15, iter.max = 100)$withinss
  wcss_list_km <- c(wcss_list_km, sum(wcss))
  rm(hca)
  rm(hca_matrix)
}
print(wcss_list)
```

```{r}
plot(test_list, wcss_list_km)
```

